### ISSUE TITLE
Irrelevant Test Cases

### ISSUE THREAD

**Issue by fayalalebrun** [ucb-bar/fixedpoint#2]
I noticed that many of the test cases included in this package don't reference FixedPoint. They seem to have been copied straight from the Chisel package. Is it a better approach to only include those tests which are relevant to the type, or is there a reason why the rest were included?

**Comment by konda-x1** [comment]
Thanks for noticing, @fayalalebrun. Yes, these tests were indeed copied from Chisel; essentially every test file that referenced FixedPoint was copied as-is and then made to work inside the context of an external library. We've since cleaned up all the test cases that had nothing to do with FixedPoint. Some of the tests were even using Chisel's FixedPoint imports instead of this library's FixedPoint, so they weren't even testing this implementation...
